spring.datasource.url=jdbc:postgresql://localhost:5432/kintai
spring.datasource.username=tw40
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
