server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Vault設定
spring.cloud.vault.token=root
spring.cloud.vault.scheme=http
spring.cloud.vault.host=vault
spring.cloud.vault.port=8200
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.default-context=kintai
spring.config.import=optional:vault://

# VaultからDBの設定を取得
spring.datasource.url=${db-url}
spring.datasource.username=${db-username}
spring.datasource.password=${db-password}
